.ALIASES
V_V1            V1(+=N00129 -=0 ) CN @LAB 5.SCHEMATIC1(sch_1):INS26@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00151 -=0 ) CN @LAB 5.SCHEMATIC1(sch_1):INS42@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00129 2=N00495 ) CN @LAB 5.SCHEMATIC1(sch_1):INS67@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=N00495 ) CN @LAB 5.SCHEMATIC1(sch_1):INS463@ANALOG.R.Normal(chips)
R_R3            R3(1=N00495 2=N00151 ) CN @LAB 5.SCHEMATIC1(sch_1):INS607@ANALOG.R.Normal(chips)
.ENDALIASES
